M48
; DRILL file {KiCad (6.0.11-0)} date Monday, February 13, 2023 at 11:09:06 AM
; FORMAT={2:4/ absolute / inch / suppress leading zeros}
; #@! TF.CreationDate,2023-02-13T11:09:06-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1083
%
G90
G05
T1
X15571Y-16760
X15571Y-36051
X38406Y-16760
X38406Y-36051
T0
M30
